### ISSUE TITLE
Copy Community Topics

### ISSUE THREAD

**Issue by AltiusRupert** [georgwittberger/sfdx-experiences-plugin#4]
Hi Georg, what is the best practice or option to copy Community Topics from one org/sandbox to another ?
My use case is Topics mapping to Knowledge Data Categories.

**Comment by georgwittberger** [comment]
Hi Rupert, I'm afraid this SFDX plugin is not what you need. It was intended to copy certain settings from one community to another within the source code, not between different orgs.

Unfortunately, I'm not familiar with Community Topics but if it's a kind of metadata you should simply use the CLI commands `force:source:retrieve` and `force:source:deploy` to download them from one org and install them on another.

Maybe this metadata component is what you are looking for? https://developer.salesforce.com/docs/atlas.en-us.api_meta.meta/api_meta/meta_managedtopics.htm

If so, try retrieving the topics using `sfdx force:source:retrieve -m ManagedTopics`

Hope it helps a bit. Good luck.
